### ISSUE TITLE
Clipboard is not working

### ISSUE THREAD

**Issue by mnaoumov** [punchy98/obsidian-remote#2]
**Describe the bug**
Clipboard is not working from host machine to the docker machine and back

**To Reproduce**

1. Try to copy some text from the host machine and insert it in the Obsidian note

**Expected behavior**
The copied text has to be pasted

**Comment by punchy98** [comment]
Cannot replicate issue. Tested with multiple systems and Obsidian versions, all are able to paste from host -> docker.
